#!/bin/bash
set -e

# Copy a default configuration into place if one not there
if [ ! -f /etc/samba/smb.conf ]; then
  cp -u -R /etc/samba.orig/* /etc/samba
fi

# Attempt to deploy pipework helper scripts
cp -u ./host-config /etc/samba || true
cp -u ./pipework /etc/samba || true

# Wait for pipework to create the bridge
if [ "${PIPEWORK_WAIT}" = "true" ]; then
  printf "Waiting for host to create eth1 interface bridge... "
  ./pipework --wait -i eth1
  echo "done."
fi

exec "$@"
